server:
  port: 8778
spring:
  application:
    name: fw-config-server
#  profiles:
#    active: native # 加载本地配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuyisu/fw-sping-cloud.git
          username: 账号
          password: 密码
          search-paths: fw-cloud-config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
