server:
  port: 8711
spring:
  application:
    name: fw-gateways-gateway
  profiles:
    active: rate_limiter_route

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
#熔断配置
spring:
  cloud:
    gateway:
      routes:
        - id: hystrix_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
            - name: Hystrix
              args:
                name: fallback
                fallbackUri: forward:/fallback/fw-cloud-ribbon-server
  profiles: hystrix_route
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
---
#熔断配置
spring:
  cloud:
    gateway:
      routes:
        - id: rate_limiter_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                key-resolver: "#{@userKeyResolver}"
  redis:
    host: ${redis.host}
    password: ${redis.pwd}
    port: 6379
  profiles: rate_limiter_route