server:
  port: 8680
spring:
  application:
    name: fw-gateways-zuul-extend
  redis:
      host: ${redis.host}
      password: ${redis.pwd}
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
#  prefix: /api  前缀，根据需要添加
  routes:
    fw-cloud-ribbon-server:
      path: /ribbon/**
